### ISSUE TITLE
Config folder is missing in source code

### ISSUE THREAD

**Issue by avinashpodisetti** [dynatrace-oss/dynatrace-gcp-function#326]
Code used to have a folder called Config, which contains list of Yaml files for every GCP service. in the latest version, this config folder is missing, but when we are running the code locally.. yaml files listed in config folder are referrenced.

**Comment by NematulloKozimov** [comment]
@avinashpodisetti config folder had been remove more than half a year ago.
here in code: src.lib.utilities.read_activation_yaml, we try to load gcp_services.yaml file which is supposed to be generated if the project dynatrace-gcp-function is deployed to GKE. Since you are trying to run the function locally, you need to create the yaml file manually and change the path accordingly.
