### ISSUE TITLE
Failed to load configuration file

### ISSUE THREAD

**Issue by avinashpodisetti** [dynatrace-oss/dynatrace-gcp-function#327]
getting following error messages for all yaml files in config folder
Failed to load configuration file: '/Users/lidsc82/Workspaces/cloudFunction/local-dyn-gcp-function-venv/source/src/config/cloud_function.yml'. Error details: unsupported type for timedelta seconds component: str

this is happening for all GCP services

**Comment by NematulloKozimov** [comment]
@avinashpodisetti config folder had been remove more than half a year ago. 
here in code: src.lib.utilities.read_activation_yaml, we try to load gcp_services.yaml file which is supposed to be generated if the project dynatrace-gcp-function is deployed to GKE. Since you are trying to run the function locally, you need to create the yaml file manually and change the path accordingly.
