### ISSUE TITLE
Adding additional Google Projects to cloud Function

### ISSUE THREAD

**Issue by dmeuth** [dynatrace-oss/dynatrace-gcp-function#47]
I have set up a project with Dynatrace Cloud Function and it is working, I have added 2 additional projects successfully, but after adding those 2 I am following the directions as I did before but an not seesin gthe new project data, when I look in the function log I do not see the new project mentioned.

Here are the gcloud project bind ID commands 

gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/monitoring.editor
gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/monitoring.viewer
gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/compute.viewer
gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/cloudsql.viewer
gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/cloudfunctions.viewer
gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/file.viewer
gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/pubsub.viewer
gcloud projects add-iam-policy-binding New-Project-Id --member="serviceAccount:dynatrace-gcp-function-pre-sa@Cloud-Function_project-35c8980e.iam.gserviceaccount.com" --role=roles/editor

where New-Project-Id is the project being added and Cloud-Function-project is the project running the cloud function app

Any ideas as to why it is failing?

**Comment by dt-be** [comment]
Have you already tried those links from the readme?

Monitoring multiple projects > https://www.dynatrace.com/support/help/shortlink/monitor-gcp#monitor-multiple-gcp-projects
Self-monitoring in Google Cloud > https://www.dynatrace.com/support/help/shortlink/troubleshoot-gcp#self-monitoring-metrics

I'd take a look at the dashboard and the self-monitoring metrics, especially this one:
Dynatrace failed requests count | The amount of requests rejected by Dynatrace metric API v2. The reason for failure can be that the data point value doesn't comply with the metric ingestion protocol syntax, or that the limit for metric ingestion is exceeded.
-- | --

If you are monitoring multiple GCP projects into the same Dynatrace tenant, it might be the trouble with limit exceeded > 
https://www.dynatrace.com/support/help/how-to-use-dynatrace/metrics/metric-ingestion/#limits
Although I'd expect in this case your other two projects might also be affected now and then, at least since the time your third project has been added. I'd recommend taking a look at the self-monitoring either way.

**Comment by dt-be** [comment]
I'm closing this ticket as there has been no response from your side, but feel free to re-open it if you still have the issue and would like to get in contact about it.
